
name: testing_sem
short_name: testing_sem

latest_version_name: Unreleased # 最新未发布的版本名称
commit_filters: # commit过滤器
  - all
version_name_with_date: true # version名称是否包含日期
version_name_with_author: true # version名称是否包含创建者
issue_uri_format: https://github.com/sandwich-go/testing_sem/issues/%s # issue地址
commit_uri_format: https://github.com/sandwich-go/testing_sem/commit/%s
merge_duplicate_commit: true # 是否合并commit相同的提交
commit_with_author_at_date: true # commit信息中是否包含作者、日期
short_hash_len: 7 # commit id长度
issue_prefix: # issue前缀 #71
  - "#"
sem_initial_version: v0.0.1 #初始版本号
sem_master_branch_name: main # 主分支名称
sem_initial_branch: 0.1 #初始的分支版本，只需major和minor


